go run sample_random.go > random_sample0.csv
go run sample_random.go > random_sample1.csv
go run sample_random.go > random_sample2.csv
go run sample_random.go > random_sample3.csv
go run sample_random.go > random_sample4.csv
go run sample_random.go > random_sample5.csv
go run sample_random.go > random_sample6.csv
go run sample_random.go > random_sample7.csv
go run sample_random.go > random_sample8.csv
go run sample_random.go > random_sample9.csv
